[build]
  command = "echo 'No build command'"
  publish = "public"
  functions = "functions"

[dev]
  publish = "public"
  functions = "functions"  # Ensure this is specified under both `build` and `dev`
